### ISSUE TITLE
[18.0] muk_web_theme -> weird popup

### ISSUE THREAD

**Issue by anhvu-sg** [muk-it/odoo-modules#12]
Firstly, I want to thank you for your hard work; the module is awesome!

However, I’ve encountered a small issue after installing it. Whenever I type any letter in a form view, search, or update any data, a popup appears immediately.

Could you please help check this?

Regards

https://github.com/user-attachments/assets/8cf8857f-a73a-404a-8570-3f5ba9d6a6cf

<img width="1305" alt="image" src="https://github.com/user-attachments/assets/6d8ff6a2-7b6f-4675-978c-e62d0cb21d04">

<img width="1120" alt="image" src="https://github.com/user-attachments/assets/fe895e13-b8b9-409a-8b9f-183016bd1e3f">

<img width="930" alt="image" src="https://github.com/user-attachments/assets/3dd561a2-c82f-4181-8b45-f4242cfd23ee">

**Comment by keshrath** [comment]
Thank you for the feedback. I will take a look asap.

**Comment by keshrath** [comment]
https://github.com/muk-it/odoo-modules/commit/b30a6c74f8f0cd87cc5e289e89f7592273d9ac29
