### ISSUE TITLE
 /muk_web_colors/static/src/scss/colors_light.scss not found in bundle web._assets_primary_variables

### ISSUE THREAD

**Issue by MYacino** [muk-it/odoo-modules#13]
File "/odoo/src/odoo/odoo/addons/base/models/ir_qweb.py", line 599, in _render

    result = ''.join(rendering)

             ^^^^^^^^^^^^^^^^^^

  File "<444>", line 67, in template_444

  File "<444>", line 56, in template_444_content

  File "<181>", line 1664, in template_181

odoo.addons.base.models.ir_qweb.QWebException: Error while render the template

ValueError: File(s) /muk_web_colors/static/src/scss/colors_light.scss not found in bundle web._assets_primary_variables

Template: web.frontend_layout

Path: /t/html/head/t[11]

Node: <t t-call-assets="web.assets_frontend" t-js="false"/>

**Comment by keshrath** [comment]
which odoo version is in use? and is the theme up-to-date? does the error also occur if the theme is uninstalled and then the latest version is installed?
