### ISSUE TITLE
v17 When you open a new record and leave it blank, it gives an error

### ISSUE THREAD

**Issue by tate11** [muk-it/odoo-modules#14]
![Muka-2024-10-14 at 19-49-22 Odoo - New](https://github.com/user-attachments/assets/d5594fd5-2c0b-4dec-8025-933408ed8052)

**Comment by keshrath** [comment]
hello, can you reproduce the error with debug=assets and post the trace?

**Comment by tate11** [comment]
> debug=assets
Formation type new icon click then discard changes icon

http://localhost:9017/web?debug=1#cids=1&menu_id=341&action=527&model=res.partner&view_type=form
UncaughtPromiseError > TypeError
Uncaught Promise > commands is undefined
TypeError: commands is undefined
    _applyCommands@http://localhost:9017/web/assets/72da7cd/web.assets_web.min.js:6337:65
    _discard@http://localhost:9017/web/assets/72da7cd/web.assets_web.min.js:6374:283
    _discard@http://localhost:9017/web/assets/72da7cd/web.assets_web.min.js:6120:142
    discard/<@http://localhost:9017/web/assets/72da7cd/web.assets_web.min.js:6078:39
    always@http://localhost:9017/web/assets/72da7cd/web.assets_web.min.js:3925:42
    
![Muk_Screenshot 2024-10-17 at 23-44-20 Odoo - New](https://github.com/user-attachments/assets/b91c3334-1607-4c22-bb95-263c40795229)

**Comment by keshrath** [comment]
unfortunately i cannot reproduce this error
