### ISSUE TITLE
Modules uninstallable - CE V18

### ISSUE THREAD

**Issue by lweiler-lab** [muk-it/odoo-modules#17]
Hello,

I cannot install your modules on Odoo18 CE. All modules are marked as uninstallable. 

Screenshot
![muk_not_installable](https://github.com/user-attachments/assets/3b875b84-bd96-4144-a78a-6eb7ece707a3)

Tried download from App Store as well as GITHub.

**Comment by keshrath** [comment]
Hello, I cannot reproduce this. I have tested all modules on both CE and EE. Try deleting the entries in the list view and then running the Update Apps List function in debug mode.

![image](https://github.com/user-attachments/assets/7c958cc5-8059-4a5e-b3de-fcf0fe9cbcac)
