### ISSUE TITLE
After change the color have error. And can not access odoo.

### ISSUE THREAD

**Issue by tangcslanyu** [muk-it/odoo-modules#4]
After change the color. The odoo down. We got this error log below. Pls kindly have a check and see how to fix it. 

Error message:

Error while render the template
ValueError: File(s) /muk_web_colors/static/src/scss/colors_light.scss not found in bundle web._assets_primary_variables
Template: website.layout
Path: /t/html/head/t[11]
Node: <t t-call-assets="web.assets_frontend" t-js="false"/>
The error occurred while rendering the template website.layout and evaluating the following expression: <t t-call-assets="web.assets_frontend" t-js="false"/>

**Comment by keshrath** [comment]
Have you try to uninstall the app and reinstall it again?

**Comment by mr-contreras** [comment]
@keshrath How can you do that if you cant login?

**Comment by roshan-socius** [comment]
@keshrath There are two files named ir.asset.py and ir.attachment.py where the website_id will be poped out, which leads to this error.After commenting those two files color changing functionality is working fine for me.
