### ISSUE TITLE
I get this error when I update the database 

### ISSUE THREAD

**Issue by tate11** [muk-it/odoo-modules#5]
[muk_web_chatter/static/src/core/chatter/chatter.xml](https://github.com/muk-it/odoo-modules/blob/1f5d12ab6ae34495700a71193307e54e9ffb4832/muk_web_chatter/static/src/core/chatter/chatter.xml#L52)
repo:muk-it/odoo-modules o-mail-Chatter-activity

**Comment by grzekru** [comment]
Same here

`odoo.addons.web.controllers.binary: Element '<xpath expr="//button[hasclass(&#39;o-mail-Chatter-activity&#39;)]/i">' cannot be located in parent view`

Testing on newest odoo 17 commit

**Comment by msdeek** [comment]
change file :
muk_web_chatter/static/src/core/chatter/chatter.xml

line 52:
form 
`<xpath expr="//button[hasclass('o-mail-Chatter-activity')]/i" position="attributes">`
to:

` <xpath expr="//button[hasclass('o-mail-Chatter-activity')]/span" position="attributes">`

**Comment by keshrath** [comment]
https://github.com/muk-it/odoo-modules/commit/19f85b9d7984b44ac8bc2bf336ceb258b8730f70
