### ISSUE TITLE
this file needs to update  muk_web_chatter/static/src/core/chatter/chatter.xml

### ISSUE THREAD

**Issue by msdeek** [muk-it/odoo-modules#6]
this file needs to update 
muk_web_chatter/static/src/core/chatter/chatter.xml

   <xpath expr="//button[hasclass('o-mail-Chatter-activity')]/i" position="attributes">
            <attribute name="class" add="me-sm-1" remove="me-1" separator=" " />
        </xpath>
        
        should be
        
           <xpath expr="//button[hasclass('o-mail-Chatter-activity')]/span" position="attributes">
            <attribute name="class" add="me-sm-1" remove="me-1" separator=" " />
        </xpath>
        
        with last update of odoo

**Comment by keshrath** [comment]
https://github.com/muk-it/odoo-modules/commit/19f85b9d7984b44ac8bc2bf336ceb258b8730f70
