### ISSUE TITLE
Screen Blank after installing muk_web_enterprise_theme

### ISSUE THREAD

**Issue by akashr355** [muk-it/odoo-modules#9]
![Screenshot from 2024-07-27 13-36-33](https://github.com/user-attachments/assets/644dcf54-2ccd-4c03-9524-6482ab3ea137)

WARNING co odoo.addons.web.controllers.binary: Parsing asset bundle web.assets_web.min.js has failed: Element '<xpath expr="//button[hasclass(&#39;o-mail-Chatter-activity&#39;)]/i">' cannot be located in parent view

**Comment by keshrath** [comment]
Unfortunately, I cannot reproduce this error
